### ISSUE TITLE
Configuration enhancement. dirty+submit, touched, touched+submit

### ISSUE THREAD

**Issue by trunkovich** [ngspot/ngx-errors#2]
## Current behavior

We are able to setup the module to show errors only for dirty inputs OR form submission. I mean if we use both `true` than we show errors only on form submission.

## Expected behavior

Show error:
1. On form control dirty OR form submitted(both cases).
2. On form control touched.
3. On form control touched OR form submitted(both cases).

## What is the motivation / use case for changing the behavior?

As a product manager, I want the user to see form errors in both cases:
- user touched(edit) form field
- user submit form

As a product manager, I want the user to see form errors when he tab through a required field without editing it.

**Comment by DmitryEfimenko** [comment]
Hello, thank you for submitting the issue. This request has made me rethink potential scenarios when the errors would need to be shown. I came up with the following:

The error messages need to be shown **after** a form is submitted - no matter what. So it does not matter what configuration is used, I can't think of a scenario when you would not want to show some errors after a form is submitted. This means that the configuration options will affect the visibility of errors only **before** the form is submitted.

Here are different strategies for displaying errors before the form is submitted:
1. Show errors right away - a rare use-case, but I've seen it in the wild
2. Show errors after the input is touched
3. Show errors after the input is dirty
4. Show errors after the input dirty OR touched
5. Show errors after the form is submitted. Meaning, don't show errors until the form is submitted, whether they inputs are dirty or touched

These use-cases aren't really described well by boolean values. For example, `showErrorsIfInputDirty: true` makes sense. It's the use-case #3. But what does `showErrorsIfInputDirty: false` mean? That's why I think it'd be better to use something like enum:
```ts
{
  displayErrorIf: 'inputIsTouched' | 'inputIsDirty' | 'inputIsDirtyOrTouched' | 'formIsSubmitted';
}
```
However, in Angular you can create a control without a form, so the 4th option there does not fit that scenario. But it really needs to be somehow included - it's a valid use-case. So maybe provide two config options for when the control has a form and when it doesn't?
```ts
{
  displayErrorIf: 'inputIsTouched' | 'inputIsDirty' | 'inputIsDirtyOrTouched' | 'formIsSubmitted';
  whenNoFormDisplayErrorIf: 'inputIsTouched' | 'inputIsDirty' | 'inputIsDirtyOrTouched';
}
```
A bit lengthy, but descriptive.

Do you have any other suggestions? Do you see any issues with described use cases?

Obviously, this would be a breaking change, so a new major version for the package.

**Comment by trunkovich** [comment]
Hello, @DmitryEfimenko 

Thank you for your fast response. First of all, I think it would be better to have this configuration about showing error after form submit. It's ok to make it default by default, but you should let users configure it if needed. I don't think you can predict all use cases.

Also I don't think that boolean configuration is a problem. Here is example of configuration and all cases covered:
```
configuration: {
  showIfDirty: boolean; // default - true
  showIfTouched: boolean; // default - false
  showOnFormSubmit: boolean; // default - true
  showOnlyAfterFormSubmit: boolean; // default - false
}
```
case 1: !showIfDirty && !showIfTouched
case 2: showIfTouched && !showIfDirty
case 3: !showIfTouched && showIfDirty
case 4: showIfTouched && showIfDirty
case 5: showOnlyAfterSubmit

I find it pretty clear. And in this case, we don't need any changes for standalone controls. Because `showOnFormSubmit` and  `showOnlyAfterFormSubmit` will be applied only for cases when we have form.

BTW, I like your idea of providing component level configuration `providers: [{ provide: ErrorsConfiguration, useValue: myConfig }]`, but maybe it's worth to add additional `@Input()` for passing configuration directly to control. I think there might be cases when it will help someone.

**Comment by DmitryEfimenko** [comment]
The proposed configuration definitely is capable of covering the outlined use-cases, but I afraid that having these boolean flags will introduce confusion since a lot of the times they are mutually exclusive. For example, what if someone uses the following config:
```ts
{
  showIfDirty: true;
  showOnlyAfterFormSubmit: true;
}
```
So what happens before the form is submitted? Do we show the error because the input is dirty or not?
Or this config:
```ts
{
  showOnFormSubmit: false;
  showOnlyAfterFormSubmit: true;
}
```
It's just confusing. I don't like the idea of dealing with all the permutations of the properties.

**Comment by trunkovich** [comment]
Do you think that `inputIsTouchedOrDirtyOrFormSubmitted` is better?

I think it's better to provide better documentation. It will include information that if `showOnlyAfterFormSubmit: true` than all other rules don't matter.

**Comment by DmitryEfimenko** [comment]
In my original proposal, the `inputTouchedOrDirty` and `formSubmitted` are mutually exclusive. `formSubmitted` means don't show errors before the form is submitted whether inputs are touched or dirty.

Here's one more argument for having this configuration as an enum. According to UX guidelines out there ((1) - [How to Report Errors in Forms](https://www.nngroup.com/articles/errors-forms-design-guidelines/), (2) - [Designing More Efficient Forms](https://uxplanet.org/designing-more-efficient-forms-assistance-and-validation-f26a5241199d)) it's best not to show an error until the user has finished with the field and moved on. This sounds like `inputIsTouched` option, but really the dev might also want to check if the input is dirty. This means a new option (which should probably also be the default one) - `inputIsDirtyAndTouched`. Note the difference with `inputIsDirtyOrTouched`. This And and Or logic can't be described by the boolean flags.

Also, regarding your comment for having an `@Input` at the control level for customization. Having an enum-like config would let us do something like this:
```html
<div ngxErrors="email" ngxErrorsShowWhen="inputIsDirty">
  <div ngxError="required">Email is required</div>
</div>
```
The above is much simpler and cleaner than having a full on JSON config object being passed in.

This conversation definitely made me go out there and do more research - thank you.
Here's the final configuration I'm planning to use:
```ts
{
  showErrorIf?: 'inputIsTouched' | 'inputIsDirty' | 'inputIsDirtyAndTouched' | 'inputIsDirtyOrTouched' | 'formIsSubmitted'; // default is `inputIsDirtyAndTouched`
  whenNoFormShowErrorIf?: 'inputIsTouched' | 'inputIsDirty' | 'inputIsDirtyAndTouched' | 'inputIsDirtyOrTouched'; // default is `inputIsDirtyAndTouched`
}
```

**Comment by trunkovich** [comment]
I don't think that field can be dirty without touching it. So dirty === dirty&touched.

**Comment by DmitryEfimenko** [comment]
> I don't think that field can be dirty without touching it. So dirty === dirty&touched.
While you're right, there is a slight, but important difference between the two scenarios. Let's take `<input type="text" />` as an example:

**The case of `inputIsDirtyOrTouched`:**
the error will show if the user
* focused on the input and started typing (`dirty`); OR
* focused on the input and moved on to another input (aka blur event) without necessarily typing anything (`touched`)

**The case of `inputIsDirtyAndTouched`:**
the error will show only if the user
* focused on the input, started typing, AND moved on to another input.

These are two different scenarios.
